[package]
name = "microtk"
version = "0.1.0"
authors = ["alienzj <alienchuj@gmail.com>"]
edition = "2018"

[dependencies]
bio = "0.32.0"
niffler = "2.3.1"
clap = "3.0.0-beta.2"

[[bin]]
name = "microtk"
path = "src/main.rs"
