[package]
name = "microtk"
version = "0.1.0"
authors = ["alienzj <alienchuj@gmail.com>"]
edition = "2018"

[dependencies]
bio = "0.31.0"
niffler = "2.2.0"
clap = "2.33.0"

[[bin]]
name = "microtk"
path = "src/microtk.rs"
